/**
 * Role-Based Access Control (RBAC) System
 * Defines permissions for different user roles
 */

// ============================================
// PERMISSION DEFINITIONS
// ============================================

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',

  // Orphan Management
  ORPHANS_VIEW: 'orphans:view',
  ORPHANS_CREATE: 'orphans:create',
  ORPHANS_EDIT: 'orphans:edit',
  ORPHANS_DELETE: 'orphans:delete',
  ORPHANS_APPROVE: 'orphans:approve',
  ORPHANS_ASSIGN_COORDINATOR: 'orphans:assign_coordinator',
  ORPHANS_REGISTER_BENEFICIARY: 'orphans:register_beneficiary',
  ORPHANS_SPONSORSHIP_MANAGE: 'orphans:sponsorship_manage',
  // Audit-hardening (2026-05): unredacted guardian NIC/phone/docs view.
  // Roles without this see redacted PII (•••).
  ORPHANS_VIEW_PII: 'orphans:view_pii',

  // Project Management
  PROJECTS_VIEW: 'projects:view',
  PROJECTS_CREATE: 'projects:create',
  PROJECTS_EDIT: 'projects:edit',
  PROJECTS_DELETE: 'projects:delete',
  PROJECTS_APPROVE: 'projects:approve',
  PROJECTS_DIRECTOR_APPROVE: 'projects:director_approve',
  PROJECTS_CEO_APPROVE: 'projects:ceo_approve',

  // Finance Management
  FINANCE_VIEW: 'finance:view',
  FINANCE_CREATE_EXPENSE: 'finance:create_expense',
  FINANCE_APPROVE_EXPENSE: 'finance:approve_expense',
  FINANCE_DELETE_EXPENSE: 'finance:delete_expense',
  FINANCE_VIEW_PAYROLL: 'finance:view_payroll',
  FINANCE_PROCESS_PAYROLL: 'finance:process_payroll',
  FINANCE_APPROVE_PO: 'finance:approve_po',
  FINANCE_MANAGER_APPROVE: 'finance:manager_approve',
  FINANCE_CEO_APPROVE: 'finance:ceo_approve',
  FINANCE_RECONCILE_ACCOUNTS: 'finance:reconcile_accounts',
  FINANCE_VIEW_REPORTS: 'finance:view_reports',

  // HR Management - General
  HR_VIEW: 'hr:view',
  HR_CREATE: 'hr:create',
  HR_EDIT: 'hr:edit',
  HR_DELETE: 'hr:delete',
  HR_VIEW_SALARY: 'hr:view_salary',
  HR_MANAGE_RECRUITMENT: 'hr:manage_recruitment',
  HR_MANAGE_PERFORMANCE: 'hr:manage_performance',

  // HR - Leave Management
  HR_APPROVE_LEAVE: 'hr:approve_leave',
  HR_MANAGER_APPROVE_LEAVE: 'hr:manager_approve_leave',

  // HR - Attendance
  HR_ATTENDANCE_MANAGE: 'hr:attendance_manage',
  HR_VIEW_ATTENDANCE: 'hr:view_attendance',
  HR_EDIT_ATTENDANCE: 'hr:edit_attendance',

  // HR - Onboarding
  HR_ONBOARDING: 'hr:onboarding',
  HR_MANAGE_ONBOARDING: 'hr:manage_onboarding',

  // HR - Appraisal
  HR_APPRAISAL: 'hr:appraisal',
  HR_MANAGE_APPRAISALS: 'hr:manage_appraisals',
  HR_CONDUCT_APPRAISALS: 'hr:conduct_appraisals',

  // HR - Contracts
  HR_MANAGE_CONTRACTS: 'hr:manage_contracts',
  HR_VIEW_CONTRACTS: 'hr:view_contracts',
  HR_CREATE_CONTRACTS: 'hr:create_contracts',
  HR_RENEW_CONTRACTS: 'hr:renew_contracts',
  HR_TERMINATE_CONTRACTS: 'hr:terminate_contracts',

  // HR - Staff Documents
  HR_DOCUMENTS_VIEW: 'hr:documents_view',
  HR_DOCUMENTS_UPLOAD: 'hr:documents_upload',
  HR_DOCUMENTS_DELETE: 'hr:documents_delete',
  HR_DOCUMENTS_APPROVE: 'hr:documents_approve',

  // CBO Management
  CBO_VIEW: 'cbo:view',
  CBO_CREATE: 'cbo:create',
  CBO_EDIT: 'cbo:edit',
  CBO_DELETE: 'cbo:delete',
  CBO_APPROVE_PROPOSAL: 'cbo:approve_proposal',
  CBO_FUNDRAISING_REVIEW: 'cbo:fundraising_review',
  CBO_PROGRAMME_MANAGER_APPROVE: 'cbo:programme_manager_approve',
  CBO_DIRECTOR_APPROVE: 'cbo:director_approve',
  CBO_CEO_APPROVE: 'cbo:ceo_approve',

  // Partners Management
  PARTNERS_VIEW: 'partners:view',
  PARTNERS_CREATE: 'partners:create',
  PARTNERS_EDIT: 'partners:edit',
  PARTNERS_DELETE: 'partners:delete',

  // Proposals Management
  PROPOSALS_VIEW: 'proposals:view',
  PROPOSALS_CREATE: 'proposals:create',
  PROPOSALS_EDIT: 'proposals:edit',
  PROPOSALS_DELETE: 'proposals:delete',
  PROPOSALS_SUBMIT: 'proposals:submit',
  PROPOSALS_APPROVE: 'proposals:approve',
  // Audit-hardening (2026-05): granular gates used by the proposal state
  // machine. STATUS_CHANGE is the umbrella perm (any transition). The
  // INTERNAL/DONOR pair separates the two review tracks — Programme
  // Manager owns internal review, Fundraising Manager owns donor side.
  PROPOSALS_STATUS_CHANGE: 'proposals:status_change',
  PROPOSALS_INTERNAL_APPROVE: 'proposals:internal_approve',
  PROPOSALS_DONOR_APPROVE: 'proposals:donor_approve',
  PROPOSALS_CONVERT: 'proposals:convert',

  // MEAL Management - General
  MEAL_VIEW: 'meal:view',
  MEAL_CREATE: 'meal:create',
  MEAL_EDIT: 'meal:edit',
  MEAL_DELETE: 'meal:delete',
  MEAL_APPROVE: 'meal:approve',
  MEAL_MONITORING: 'meal:monitoring',

  // MEAL - Evaluations
  MEAL_EVALUATION: 'meal:evaluation',
  MEAL_EVALUATION_CREATE: 'meal:evaluation_create',
  MEAL_EVALUATION_EDIT: 'meal:evaluation_edit',
  MEAL_EVALUATION_DELETE: 'meal:evaluation_delete',

  // MEAL - Learning Events
  MEAL_LEARNING_EVENTS_VIEW: 'meal:learning_events_view',
  MEAL_LEARNING_EVENTS_CREATE: 'meal:learning_events_create',
  MEAL_LEARNING_EVENTS_EDIT: 'meal:learning_events_edit',
  MEAL_LEARNING_EVENTS_DELETE: 'meal:learning_events_delete',

  // MEAL - Indicators
  MEAL_INDICATORS_VIEW: 'meal:indicators_view',
  MEAL_INDICATORS_CREATE: 'meal:indicators_create',
  MEAL_INDICATORS_EDIT: 'meal:indicators_edit',
  MEAL_INDICATORS_UPDATE: 'meal:indicators_update',
  MEAL_INDICATORS_DELETE: 'meal:indicators_delete',

  // Campaigns Management
  CAMPAIGNS_VIEW: 'campaigns:view',
  CAMPAIGNS_CREATE: 'campaigns:create',
  CAMPAIGNS_EDIT: 'campaigns:edit',
  CAMPAIGNS_DELETE: 'campaigns:delete',
  CAMPAIGNS_APPROVE: 'campaigns:approve',
  CAMPAIGNS_BUDGET_MANAGE: 'campaigns:budget_manage',

  // Campaigns - Packages
  CAMPAIGNS_PACKAGES_VIEW: 'campaigns:packages_view',
  CAMPAIGNS_PACKAGES_CREATE: 'campaigns:packages_create',
  CAMPAIGNS_PACKAGES_EDIT: 'campaigns:packages_edit',
  CAMPAIGNS_PACKAGES_DELETE: 'campaigns:packages_delete',

  // Donations Management
  DONATIONS_VIEW: 'donations:view',
  DONATIONS_CREATE: 'donations:create',
  DONATIONS_EDIT: 'donations:edit',
  DONATIONS_DELETE: 'donations:delete',

  // Social Media Management
  SOCIAL_MEDIA_VIEW: 'social_media:view',
  SOCIAL_MEDIA_CREATE: 'social_media:create',
  SOCIAL_MEDIA_PUBLISH: 'social_media:publish',
  SOCIAL_MEDIA_DELETE: 'social_media:delete',

  // Job Postings Management
  JOB_POSTINGS_VIEW: 'job_postings:view',
  JOB_POSTINGS_CREATE: 'job_postings:create',
  JOB_POSTINGS_EDIT: 'job_postings:edit',
  JOB_POSTINGS_DELETE: 'job_postings:delete',

  // Vendor Calls/Tenders Management
  VENDOR_CALLS_VIEW: 'vendor_calls:view',
  VENDOR_CALLS_CREATE: 'vendor_calls:create',
  VENDOR_CALLS_EDIT: 'vendor_calls:edit',
  VENDOR_CALLS_DELETE: 'vendor_calls:delete',

  // Operations - Activities
  OPERATIONS_VIEW_ACTIVITIES: 'operations:view_activities',
  OPERATIONS_CREATE_ACTIVITY: 'operations:create_activity',
  OPERATIONS_EDIT_ACTIVITY: 'operations:edit_activity',
  OPERATIONS_DELETE_ACTIVITY: 'operations:delete_activity',

  // Operations - Tasks
  OPERATIONS_VIEW_TASKS: 'operations:view_tasks',
  OPERATIONS_CREATE_TASK: 'operations:create_task',
  OPERATIONS_EDIT_TASK: 'operations:edit_task',
  OPERATIONS_DELETE_TASK: 'operations:delete_task',
  OPERATIONS_ASSIGN_TASK: 'operations:assign_task',
  OPERATIONS_UPDATE_TASK_PROGRESS: 'operations:update_task_progress',
  OPERATIONS_COMPLETE_TASK: 'operations:complete_task',
  OPERATIONS_MY_TASKS: 'operations:my_tasks', // View own tasks (available to all)

  // Approvals
  APPROVALS_VIEW: 'approvals:view',
  APPROVALS_MANAGE: 'approvals:manage',

  // Reports & Compliance
  REPORTS_VIEW: 'reports:view',
  REPORTS_CREATE: 'reports:create',
  REPORTS_GENERATE: 'reports:generate',
  REPORTS_EDIT: 'reports:edit',
  REPORTS_DELETE: 'reports:delete',
  REPORTS_EXPORT: 'reports:export',
  COMPLIANCE_VIEW: 'compliance:view',
  COMPLIANCE_MANAGE: 'compliance:manage',

  // System Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',
  SETTINGS_ROLES_MANAGE: 'settings:roles_manage',
  SYSTEM_SETTINGS: 'system:settings',

  // User Management
  USERS_VIEW: 'users:view',
  USERS_CREATE: 'users:create',
  USERS_EDIT: 'users:edit',
  USERS_DELETE: 'users:delete',

  // Beneficiary Management
  BENEFICIARIES_VIEW: 'beneficiaries:view',
  BENEFICIARIES_CREATE: 'beneficiaries:create',
  BENEFICIARIES_EDIT: 'beneficiaries:edit',
  BENEFICIARIES_DELETE: 'beneficiaries:delete',

  // WASH Programme (audit-hardening 2026-05) — order = donor commitment,
  // stage updates = on-the-ground delivery progress.
  WASH_VIEW: 'wash:view',
  WASH_ORDER_WRITE: 'wash:order_write',
  WASH_STAGE_UPDATE: 'wash:stage_update',

  // IGP Programme (income-generating asset distribution).
  IGP_VIEW: 'igp:view',
  IGP_ORDER_WRITE: 'igp:order_write',
  IGP_STAGE_UPDATE: 'igp:stage_update',

  // BeneficiarySupport approvals (gates createSupport for unapproved orphans).
  BENEFICIARY_SUPPORT_APPROVE: 'beneficiary_support:approve',

  // Procurement
  PROCUREMENT_DASHBOARD_VIEW: 'procurement:dashboard:view',
  PROCUREMENT_REQUEST_VIEW: 'procurement:request:view',
  PROCUREMENT_REQUEST_CREATE: 'procurement:request:create',
  PROCUREMENT_REQUEST_ASSIGN: 'procurement:request:assign',
  PROCUREMENT_REQUEST_CANCEL: 'procurement:request:cancel',
  PROCUREMENT_RFQ_CREATE: 'procurement:rfq:create',
  PROCUREMENT_RFQ_SEND: 'procurement:rfq:send',
  PROCUREMENT_QUOTATION_ENTER: 'procurement:quotation:enter',
  PROCUREMENT_BID_ANALYSIS_CREATE: 'procurement:bid_analysis:create',
  PROCUREMENT_BID_ANALYSIS_APPROVE: 'procurement:bid_analysis:approve',
  PROCUREMENT_PO_DRAFT: 'procurement:po:draft',
  PROCUREMENT_PO_APPROVE: 'procurement:po:approve',
  PROCUREMENT_PO_ISSUE: 'procurement:po:issue',
  PROCUREMENT_GRN_CREATE: 'procurement:goods_receipt:create',
  PROCUREMENT_GRN_VERIFY: 'procurement:goods_receipt:verify',
  PROCUREMENT_INVOICE_MATCH: 'procurement:invoice:match',
  PROCUREMENT_VENDOR_VIEW: 'procurement:vendor:view',
  PROCUREMENT_VENDOR_CREATE: 'procurement:vendor:create',
  PROCUREMENT_VENDOR_EDIT: 'procurement:vendor:edit',
  PROCUREMENT_VENDOR_BLACKLIST: 'procurement:vendor:blacklist',
  PROCUREMENT_THRESHOLDS_MANAGE: 'procurement:thresholds:manage',
  PROCUREMENT_REPORT_VIEW: 'procurement:report:view',

  // Finance — Cash module
  CASH_ACCOUNTS_VIEW: 'finance:cash:accounts:view',
  CASH_ACCOUNTS_MANAGE: 'finance:cash:accounts:manage',
  CASH_TRANSACTIONS_VIEW: 'finance:cash:transactions:view',
  CASH_TRANSACTIONS_RECORD: 'finance:cash:transactions:record',
  CASH_TRANSACTIONS_APPROVE: 'finance:cash:transactions:approve',
  CASH_COUNT_RUN: 'finance:cash:count:run',
  CASH_COUNT_APPROVE: 'finance:cash:count:approve',
  CASH_REPLENISHMENT_REQUEST: 'finance:cash:replenishment:request',
  CASH_REPLENISHMENT_APPROVE: 'finance:cash:replenishment:approve',
};

// ============================================
// ROLE PERMISSIONS MAPPING
// ============================================

export const ROLE_PERMISSIONS = {
  // Level 0: System Administrator
  'Admin': [
    // Full access to everything
    ...Object.values(PERMISSIONS),
  ],

  // Level 1: Governance
  'BOD': [
    // Board of Directors - Strategic oversight, view all modules
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_VIEW_REPORTS,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  // Level 2: Executive Leadership
  'CEO': [
    // CEO - Executive authority, can approve everything
    PERMISSIONS.DASHBOARD_VIEW,

    // View all modules
    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_APPROVE,
    PERMISSIONS.ORPHANS_SPONSORSHIP_MANAGE,

    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.BENEFICIARIES_EDIT,
    PERMISSIONS.BENEFICIARIES_DELETE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CEO_APPROVE,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CEO_APPROVE,
    PERMISSIONS.FINANCE_VIEW_REPORTS,
    PERMISSIONS.FINANCE_VIEW_PAYROLL,

    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_MANAGER_APPROVE_LEAVE,
    PERMISSIONS.HR_VIEW_SALARY,

    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.CBO_CEO_APPROVE,

    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.PARTNERS_CREATE,
    PERMISSIONS.PARTNERS_EDIT,

    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.PROPOSALS_APPROVE,
    PERMISSIONS.PROPOSALS_STATUS_CHANGE,
    PERMISSIONS.PROPOSALS_INTERNAL_APPROVE,
    PERMISSIONS.PROPOSALS_DONOR_APPROVE,
    PERMISSIONS.PROPOSALS_CONVERT,

    // Programme oversight (read) + PII view for CEO escalation cases.
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.IGP_VIEW,
    PERMISSIONS.ORPHANS_VIEW_PII,
    PERMISSIONS.BENEFICIARY_SUPPORT_APPROVE,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_APPROVE,
    PERMISSIONS.MEAL_EVALUATION,
    PERMISSIONS.MEAL_EVALUATION_CREATE,
    PERMISSIONS.MEAL_EVALUATION_EDIT,
    PERMISSIONS.MEAL_EVALUATION_DELETE,
    PERMISSIONS.MEAL_LEARNING_EVENTS_VIEW,
    PERMISSIONS.MEAL_LEARNING_EVENTS_CREATE,
    PERMISSIONS.MEAL_LEARNING_EVENTS_EDIT,
    PERMISSIONS.MEAL_LEARNING_EVENTS_DELETE,
    PERMISSIONS.MEAL_INDICATORS_VIEW,
    PERMISSIONS.MEAL_INDICATORS_CREATE,
    PERMISSIONS.MEAL_INDICATORS_EDIT,
    PERMISSIONS.MEAL_INDICATORS_UPDATE,

    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.CAMPAIGNS_APPROVE,
    PERMISSIONS.CAMPAIGNS_PACKAGES_VIEW,
    PERMISSIONS.CAMPAIGNS_PACKAGES_CREATE,
    PERMISSIONS.CAMPAIGNS_PACKAGES_EDIT,

    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.SOCIAL_MEDIA_VIEW,
    PERMISSIONS.JOB_POSTINGS_VIEW,
    PERMISSIONS.VENDOR_CALLS_VIEW,

    PERMISSIONS.OPERATIONS_VIEW_ACTIVITIES,
    PERMISSIONS.OPERATIONS_CREATE_ACTIVITY,
    PERMISSIONS.OPERATIONS_EDIT_ACTIVITY,
    PERMISSIONS.OPERATIONS_DELETE_ACTIVITY,

    PERMISSIONS.OPERATIONS_VIEW_TASKS,
    PERMISSIONS.OPERATIONS_CREATE_TASK,
    PERMISSIONS.OPERATIONS_EDIT_TASK,
    PERMISSIONS.OPERATIONS_DELETE_TASK,
    PERMISSIONS.OPERATIONS_ASSIGN_TASK,
    PERMISSIONS.OPERATIONS_UPDATE_TASK_PROGRESS,
    PERMISSIONS.OPERATIONS_COMPLETE_TASK,
    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.APPROVALS_MANAGE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,

    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.COMPLIANCE_MANAGE,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.USERS_VIEW,
  ],

  // Level 3: Directors
  'Director Programmes': [
    // Director - Programme oversight and approval
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_APPROVE,
    PERMISSIONS.ORPHANS_ASSIGN_COORDINATOR,

    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.BENEFICIARIES_EDIT,
    PERMISSIONS.BENEFICIARIES_DELETE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_DIRECTOR_APPROVE,

    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.CBO_DIRECTOR_APPROVE,

    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.PROPOSALS_CREATE,
    PERMISSIONS.PROPOSALS_EDIT,
    PERMISSIONS.PROPOSALS_APPROVE,
    PERMISSIONS.PROPOSALS_STATUS_CHANGE,
    PERMISSIONS.PROPOSALS_INTERNAL_APPROVE,
    PERMISSIONS.PROPOSALS_CONVERT,

    // Programme oversight (read + write) for sign-off & escalation.
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.WASH_ORDER_WRITE,
    PERMISSIONS.WASH_STAGE_UPDATE,
    PERMISSIONS.IGP_VIEW,
    PERMISSIONS.IGP_ORDER_WRITE,
    PERMISSIONS.IGP_STAGE_UPDATE,
    PERMISSIONS.ORPHANS_VIEW_PII,
    PERMISSIONS.BENEFICIARY_SUPPORT_APPROVE,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_APPROVE,
    PERMISSIONS.MEAL_EVALUATION,
    PERMISSIONS.MEAL_EVALUATION_CREATE,
    PERMISSIONS.MEAL_EVALUATION_EDIT,
    PERMISSIONS.MEAL_LEARNING_EVENTS_VIEW,
    PERMISSIONS.MEAL_LEARNING_EVENTS_CREATE,
    PERMISSIONS.MEAL_LEARNING_EVENTS_EDIT,
    PERMISSIONS.MEAL_INDICATORS_VIEW,
    PERMISSIONS.MEAL_INDICATORS_UPDATE,

    PERMISSIONS.OPERATIONS_VIEW_ACTIVITIES,
    PERMISSIONS.OPERATIONS_CREATE_ACTIVITY,
    PERMISSIONS.OPERATIONS_EDIT_ACTIVITY,
    PERMISSIONS.OPERATIONS_VIEW_TASKS,
    PERMISSIONS.OPERATIONS_CREATE_TASK,
    PERMISSIONS.OPERATIONS_EDIT_TASK,
    PERMISSIONS.OPERATIONS_ASSIGN_TASK,
    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.FINANCE_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,

    PERMISSIONS.SETTINGS_VIEW,
  ],

  // Level 4: Managers
  'Programme Manager': [
    // Programme Manager - Manages all programme activities
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_APPROVE,
    PERMISSIONS.ORPHANS_ASSIGN_COORDINATOR,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,

    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.BENEFICIARIES_EDIT,
    PERMISSIONS.BENEFICIARIES_DELETE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.PROJECTS_APPROVE,

    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.CBO_EDIT,
    PERMISSIONS.CBO_PROGRAMME_MANAGER_APPROVE,

    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.PROPOSALS_CREATE,
    PERMISSIONS.PROPOSALS_EDIT,
    // Programme Manager runs the internal review track + signs proposals
    // off for the donor side. Conversion moves money so PM holds that perm.
    PERMISSIONS.PROPOSALS_STATUS_CHANGE,
    PERMISSIONS.PROPOSALS_INTERNAL_APPROVE,
    PERMISSIONS.PROPOSALS_CONVERT,

    // Direct ownership of WASH/IGP order pipeline.
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.WASH_ORDER_WRITE,
    PERMISSIONS.WASH_STAGE_UPDATE,
    PERMISSIONS.IGP_VIEW,
    PERMISSIONS.IGP_ORDER_WRITE,
    PERMISSIONS.IGP_STAGE_UPDATE,
    PERMISSIONS.ORPHANS_VIEW_PII,
    PERMISSIONS.BENEFICIARY_SUPPORT_APPROVE,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,
    PERMISSIONS.MEAL_APPROVE,
    PERMISSIONS.MEAL_EVALUATION,
    PERMISSIONS.MEAL_EVALUATION_CREATE,
    PERMISSIONS.MEAL_EVALUATION_EDIT,
    PERMISSIONS.MEAL_LEARNING_EVENTS_VIEW,
    PERMISSIONS.MEAL_LEARNING_EVENTS_CREATE,
    PERMISSIONS.MEAL_LEARNING_EVENTS_EDIT,
    PERMISSIONS.MEAL_INDICATORS_VIEW,
    PERMISSIONS.MEAL_INDICATORS_CREATE,
    PERMISSIONS.MEAL_INDICATORS_EDIT,
    PERMISSIONS.MEAL_INDICATORS_UPDATE,

    PERMISSIONS.OPERATIONS_VIEW_ACTIVITIES,
    PERMISSIONS.OPERATIONS_CREATE_ACTIVITY,
    PERMISSIONS.OPERATIONS_EDIT_ACTIVITY,
    PERMISSIONS.OPERATIONS_VIEW_TASKS,
    PERMISSIONS.OPERATIONS_CREATE_TASK,
    PERMISSIONS.OPERATIONS_EDIT_TASK,
    PERMISSIONS.OPERATIONS_DELETE_TASK,
    PERMISSIONS.OPERATIONS_ASSIGN_TASK,
    PERMISSIONS.OPERATIONS_UPDATE_TASK_PROGRESS,
    PERMISSIONS.OPERATIONS_COMPLETE_TASK,
    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_APPROVE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,

    PERMISSIONS.APPROVALS_VIEW,
  ],

  'Finance Manager': [
    // Finance Manager - Full finance management
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,
    PERMISSIONS.FINANCE_APPROVE_EXPENSE,
    PERMISSIONS.FINANCE_DELETE_EXPENSE,
    PERMISSIONS.FINANCE_VIEW_PAYROLL,
    PERMISSIONS.FINANCE_PROCESS_PAYROLL,
    PERMISSIONS.FINANCE_APPROVE_PO,
    PERMISSIONS.FINANCE_MANAGER_APPROVE,
    PERMISSIONS.FINANCE_RECONCILE_ACCOUNTS,
    PERMISSIONS.FINANCE_VIEW_REPORTS,

    PERMISSIONS.CASH_ACCOUNTS_VIEW,
    PERMISSIONS.CASH_ACCOUNTS_MANAGE,
    PERMISSIONS.CASH_TRANSACTIONS_VIEW,
    PERMISSIONS.CASH_TRANSACTIONS_RECORD,
    PERMISSIONS.CASH_TRANSACTIONS_APPROVE,
    PERMISSIONS.CASH_COUNT_RUN,
    PERMISSIONS.CASH_COUNT_APPROVE,
    PERMISSIONS.CASH_REPLENISHMENT_REQUEST,
    PERMISSIONS.CASH_REPLENISHMENT_APPROVE,

    // View other modules for context
    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.IGP_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,

    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  'Fundraising Manager': [
    // Fundraising Manager - Manage fundraising and campaigns
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.CBO_FUNDRAISING_REVIEW,

    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.PARTNERS_CREATE,
    PERMISSIONS.PARTNERS_EDIT,

    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.PROPOSALS_CREATE,
    PERMISSIONS.PROPOSALS_EDIT,
    // Fundraising owns the donor-facing track: submitting to donor, marking
    // Donor Approved/Rejected, converting accepted proposals into orders.
    PERMISSIONS.PROPOSALS_STATUS_CHANGE,
    PERMISSIONS.PROPOSALS_DONOR_APPROVE,
    PERMISSIONS.PROPOSALS_CONVERT,

    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.CAMPAIGNS_CREATE,
    PERMISSIONS.CAMPAIGNS_EDIT,
    PERMISSIONS.CAMPAIGNS_APPROVE,
    PERMISSIONS.CAMPAIGNS_BUDGET_MANAGE,

    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.DONATIONS_CREATE,
    PERMISSIONS.DONATIONS_EDIT,

    PERMISSIONS.SOCIAL_MEDIA_VIEW,
    PERMISSIONS.SOCIAL_MEDIA_CREATE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.MEAL_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,

    PERMISSIONS.APPROVALS_VIEW,
  ],

  'HR Manager': [
    // HR Manager - Full HR management
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.HR_APPROVE_LEAVE,
    PERMISSIONS.HR_MANAGER_APPROVE_LEAVE,
    PERMISSIONS.HR_VIEW_SALARY,
    PERMISSIONS.HR_MANAGE_RECRUITMENT,
    PERMISSIONS.HR_MANAGE_PERFORMANCE,
    PERMISSIONS.HR_ATTENDANCE_MANAGE,
    PERMISSIONS.HR_ONBOARDING,
    PERMISSIONS.HR_APPRAISAL,
    PERMISSIONS.HR_VIEW_ATTENDANCE,
    PERMISSIONS.HR_MANAGE_ONBOARDING,
    PERMISSIONS.HR_MANAGE_APPRAISALS,
    PERMISSIONS.HR_MANAGE_CONTRACTS,

    PERMISSIONS.FINANCE_VIEW_PAYROLL,
    PERMISSIONS.FINANCE_PROCESS_PAYROLL,

    PERMISSIONS.JOB_POSTINGS_VIEW,
    PERMISSIONS.JOB_POSTINGS_CREATE,
    PERMISSIONS.JOB_POSTINGS_EDIT,
    PERMISSIONS.JOB_POSTINGS_DELETE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.ORPHANS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,

    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.USERS_VIEW,
  ],

  // Level 5: Officers
  'Project Officer WASH': [
    // Project Officer (WASH specialization)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,

    // Owns the WASH order pipeline for their projects.
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.WASH_ORDER_WRITE,
    PERMISSIONS.WASH_STAGE_UPDATE,
    // Read-only awareness of IGP for cross-programme reporting.
    PERMISSIONS.IGP_VIEW,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,
    PERMISSIONS.MEAL_MONITORING,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer (WASH)': [
    // Alias for Project Officer WASH - matches database role name
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,

    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.WASH_ORDER_WRITE,
    PERMISSIONS.WASH_STAGE_UPDATE,
    PERMISSIONS.IGP_VIEW,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,
    PERMISSIONS.MEAL_MONITORING,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer Orphans': [
    // Project Officer (Orphans specialization)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,
    PERMISSIONS.ORPHANS_ASSIGN_COORDINATOR,
    PERMISSIONS.ORPHANS_SPONSORSHIP_MANAGE,
    // Sees full PII because they manage sponsor matching and guardian docs.
    PERMISSIONS.ORPHANS_VIEW_PII,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer (Orphans)': [
    // Alias for Project Officer Orphans - matches database role name
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,
    PERMISSIONS.ORPHANS_ASSIGN_COORDINATOR,
    PERMISSIONS.ORPHANS_SPONSORSHIP_MANAGE,
    PERMISSIONS.ORPHANS_VIEW_PII,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer Livelihoods': [
    // Project Officer (Livelihoods specialization)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer Infrastructure': [
    // Project Officer (Infrastructure specialization)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.VENDOR_CALLS_VIEW,
    PERMISSIONS.VENDOR_CALLS_CREATE,
    PERMISSIONS.VENDOR_CALLS_EDIT,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer Education': [
    // Project Officer (Education specialization)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer Women': [
    // Project Officer (Women Development specialization)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,
    PERMISSIONS.ORPHANS_REGISTER_BENEFICIARY,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Project Officer': [
    // Generic Project Officer (for backward compatibility)
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Field Officer': [
    // Field Officer - Field operations
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_EDIT,

    PERMISSIONS.PROJECTS_VIEW,

    // Field officers are the actual hands on WASH/IGP delivery. They can
    // see and update stages on items they're assigned to. The controller
    // additionally checks assignedSupervisorId so they can't touch
    // someone else's items.
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.WASH_STAGE_UPDATE,
    PERMISSIONS.IGP_VIEW,
    PERMISSIONS.IGP_STAGE_UPDATE,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Finance Officer': [
    // Finance Officer
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,
    PERMISSIONS.FINANCE_VIEW_PAYROLL,

    PERMISSIONS.CASH_ACCOUNTS_VIEW,
    PERMISSIONS.CASH_TRANSACTIONS_VIEW,
    PERMISSIONS.CASH_TRANSACTIONS_RECORD,
    PERMISSIONS.CASH_COUNT_RUN,
    PERMISSIONS.CASH_REPLENISHMENT_REQUEST,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'HR Officer': [
    // HR Officer
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_APPROVE_LEAVE,
    PERMISSIONS.HR_ATTENDANCE_MANAGE,
    PERMISSIONS.HR_VIEW_ATTENDANCE,
    PERMISSIONS.HR_ONBOARDING,
    PERMISSIONS.HR_MANAGE_ONBOARDING,
    PERMISSIONS.HR_MANAGE_CONTRACTS,

    PERMISSIONS.JOB_POSTINGS_VIEW,
    PERMISSIONS.JOB_POSTINGS_CREATE,
    PERMISSIONS.JOB_POSTINGS_EDIT,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,

    PERMISSIONS.USERS_VIEW,
  ],

  'MEAL Officer': [
    // MEAL Officer - Monitoring, Evaluation, Accountability, Learning
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,
    PERMISSIONS.MEAL_EDIT,
    PERMISSIONS.MEAL_DELETE,
    PERMISSIONS.MEAL_MONITORING,
    PERMISSIONS.MEAL_EVALUATION,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.CBO_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    // MEAL captures verification stage updates against delivered items.
    PERMISSIONS.WASH_VIEW,
    PERMISSIONS.WASH_STAGE_UPDATE,
    PERMISSIONS.IGP_VIEW,
    PERMISSIONS.IGP_STAGE_UPDATE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  'Media Production Officer': [
    // Media Production Officer
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.SOCIAL_MEDIA_VIEW,
    PERMISSIONS.SOCIAL_MEDIA_CREATE,
    PERMISSIONS.SOCIAL_MEDIA_PUBLISH,

    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.CAMPAIGNS_CREATE,
    PERMISSIONS.CAMPAIGNS_EDIT,

    PERMISSIONS.DONATIONS_VIEW,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.ORPHANS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Media Officer': [
    // Media Officer
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.SOCIAL_MEDIA_VIEW,
    PERMISSIONS.SOCIAL_MEDIA_CREATE,

    PERMISSIONS.CAMPAIGNS_VIEW,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Accountant': [
    // Accountant
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,
    PERMISSIONS.FINANCE_VIEW_PAYROLL,
    PERMISSIONS.FINANCE_RECONCILE_ACCOUNTS,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
  ],

  'Procurement Manager': [
    // Owns the procurement function: assigns work, approves vendor selection,
    // signs POs above threshold, manages vendor master + thresholds.
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROCUREMENT_DASHBOARD_VIEW,
    PERMISSIONS.PROCUREMENT_REQUEST_VIEW,
    PERMISSIONS.PROCUREMENT_REQUEST_CREATE,
    PERMISSIONS.PROCUREMENT_REQUEST_ASSIGN,
    PERMISSIONS.PROCUREMENT_REQUEST_CANCEL,
    PERMISSIONS.PROCUREMENT_RFQ_CREATE,
    PERMISSIONS.PROCUREMENT_RFQ_SEND,
    PERMISSIONS.PROCUREMENT_QUOTATION_ENTER,
    PERMISSIONS.PROCUREMENT_BID_ANALYSIS_CREATE,
    PERMISSIONS.PROCUREMENT_BID_ANALYSIS_APPROVE,
    PERMISSIONS.PROCUREMENT_PO_DRAFT,
    PERMISSIONS.PROCUREMENT_PO_APPROVE,
    PERMISSIONS.PROCUREMENT_PO_ISSUE,
    PERMISSIONS.PROCUREMENT_GRN_CREATE,
    PERMISSIONS.PROCUREMENT_GRN_VERIFY,
    PERMISSIONS.PROCUREMENT_INVOICE_MATCH,
    PERMISSIONS.PROCUREMENT_VENDOR_VIEW,
    PERMISSIONS.PROCUREMENT_VENDOR_CREATE,
    PERMISSIONS.PROCUREMENT_VENDOR_EDIT,
    PERMISSIONS.PROCUREMENT_VENDOR_BLACKLIST,
    PERMISSIONS.PROCUREMENT_THRESHOLDS_MANAGE,
    PERMISSIONS.PROCUREMENT_REPORT_VIEW,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.APPROVALS_MANAGE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  'Procurement Officer': [
    // Day-to-day procurement: handles RFQs, captures quotations, drafts POs,
    // verifies GRNs, performs 3-way match. No vendor blacklist, no threshold edits.
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.OPERATIONS_MY_TASKS,

    PERMISSIONS.PROCUREMENT_DASHBOARD_VIEW,
    PERMISSIONS.PROCUREMENT_REQUEST_VIEW,
    PERMISSIONS.PROCUREMENT_REQUEST_CREATE,
    PERMISSIONS.PROCUREMENT_RFQ_CREATE,
    PERMISSIONS.PROCUREMENT_RFQ_SEND,
    PERMISSIONS.PROCUREMENT_QUOTATION_ENTER,
    PERMISSIONS.PROCUREMENT_BID_ANALYSIS_CREATE,
    PERMISSIONS.PROCUREMENT_PO_DRAFT,
    PERMISSIONS.PROCUREMENT_GRN_CREATE,
    PERMISSIONS.PROCUREMENT_GRN_VERIFY,
    PERMISSIONS.PROCUREMENT_INVOICE_MATCH,
    PERMISSIONS.PROCUREMENT_VENDOR_VIEW,
    PERMISSIONS.PROCUREMENT_VENDOR_CREATE,
    PERMISSIONS.PROCUREMENT_VENDOR_EDIT,
    PERMISSIONS.PROCUREMENT_REPORT_VIEW,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  // Level 6: Assistants
  'Project Assistant': [
    // Project Assistant - Support project officers
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_CREATE,
    PERMISSIONS.ORPHANS_EDIT,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_EDIT,

    PERMISSIONS.MEAL_VIEW,
    PERMISSIONS.MEAL_CREATE,

    PERMISSIONS.CBO_VIEW,

    PERMISSIONS.FINANCE_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Finance Assistant': [
    // Finance Assistant
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE_EXPENSE,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'Fundraising Assistant': [
    // Fundraising Assistant
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CAMPAIGNS_VIEW,
    PERMISSIONS.CAMPAIGNS_CREATE,

    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.DONATIONS_CREATE,

    PERMISSIONS.SOCIAL_MEDIA_VIEW,

    PERMISSIONS.PARTNERS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  'HR Assistant': [
    // HR Assistant
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_ATTENDANCE_MANAGE,
    PERMISSIONS.HR_VIEW_ATTENDANCE,

    PERMISSIONS.JOB_POSTINGS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  // Level 7: Coordinators
  'Orphan Coordinator': [
    // Orphan Coordinator - Focused on orphan care
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORPHANS_VIEW,
    PERMISSIONS.ORPHANS_EDIT,
    // Coordinators interact with families weekly; they need the guardian
    // contact info and IDs to do visits and verification.
    PERMISSIONS.ORPHANS_VIEW_PII,

    PERMISSIONS.PROJECTS_VIEW,

    PERMISSIONS.MEAL_VIEW,

    PERMISSIONS.REPORTS_VIEW,
  ],

  // Guest (lowest level)
  'Guest': [
    // Read-only access to non-sensitive data
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
};

// ============================================
// PERMISSION CHECKING FUNCTIONS
// ============================================

/**
 * Check if a user has a specific permission
 * @param {object} user - User object with role property
 * @param {string} permission - Permission to check
 * @returns {boolean} True if user has permission
 */
export const hasPermission = (user, permission) => {
  if (!user || !user.role) return false;

  const rolePermissions = ROLE_PERMISSIONS[user.role] || [];
  return rolePermissions.includes(permission);
};

/**
 * Check if user has any of the specified permissions
 * @param {object} user - User object with role property
 * @param {string[]} permissions - Array of permissions to check
 * @returns {boolean} True if user has at least one permission
 */
export const hasAnyPermission = (user, permissions) => {
  if (!user || !user.role) return false;

  const rolePermissions = ROLE_PERMISSIONS[user.role] || [];
  return permissions.some(permission => rolePermissions.includes(permission));
};

/**
 * Check if user has all specified permissions
 * @param {object} user - User object with role property
 * @param {string[]} permissions - Array of permissions to check
 * @returns {boolean} True if user has all permissions
 */
export const hasAllPermissions = (user, permissions) => {
  if (!user || !user.role) return false;

  const rolePermissions = ROLE_PERMISSIONS[user.role] || [];
  return permissions.every(permission => rolePermissions.includes(permission));
};

/**
 * Get all permissions for a user role
 * @param {string} role - User role
 * @returns {string[]} Array of permissions
 */
export const getPermissionsForRole = (role) => {
  return ROLE_PERMISSIONS[role] || [];
};

/**
 * Check if user is admin
 * @param {object} user - User object
 * @returns {boolean} True if user is admin
 */
export const isAdmin = (user) => {
  return user?.role === 'Admin';
};

/**
 * Check if user is CEO
 * @param {object} user - User object
 * @returns {boolean} True if user is CEO
 */
export const isCEO = (user) => {
  return user?.role === 'CEO';
};

/**
 * Check if user can approve (Admin or CEO)
 * @param {object} user - User object
 * @returns {boolean} True if user can approve high-level items
 */
export const canApprove = (user) => {
  return isAdmin(user) || isCEO(user);
};

// ============================================
// DEFAULT EXPORT
// ============================================

export default {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getPermissionsForRole,
  isAdmin,
  isCEO,
  canApprove,
};
